USE [SVC_CarAuctionManagement];

CREATE TABLE [dbo].[User]
(
	[Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[CreatedDate]	DATETIMEOFFSET(3)	NOT NULL,
	[Name]			VARCHAR(100)		NOT NULL,
	CONSTRAINT [PK_User_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);